### ISSUE TITLE
Symfony 3.3 deprecation notice

### ISSUE THREAD

**Issue by pevdh** [cocur/slugify#179]
Just a heads up:

> Autowiring services based on the types they implement is deprecated since Symfony 3.3 and won't be supported in version 4.0. You should rename (or alias) the "cocur_slugify" service to "Cocur\Slugify\SlugifyInterface" instead.

**Comment by FabienPapet** [comment]
In your services.yml file just write
``` yml
Cocur\Slugify\SlugifyInterface:
    alias: cocur_slugify
```

**Comment by pevdh** [comment]
Yes, I should have noted that that works just fine. However, actually renaming the service would be nice in the long run (I hate such implementation details in my services.yml, but that might just be me).

**Comment by florianeckerstorfer** [comment]
Can someone that uses Symfony 3.3 create an PR? Is the new version compatible with old versions of Symfony?

**Comment by FabienPapet** [comment]
As far as I know, older versions of Symfony don't allow namespaces as service names. Perhaps we can add a version checker and correct this only for version > 3.3 ?

**Comment by florianeckerstorfer** [comment]
Since I'm not using Symfony right now can you create a PR? I would really appreciate it.

**Comment by FabienPapet** [comment]
I'll try to work on it this week-end.

**Comment by florianeckerstorfer** [comment]
Fixed by #185. Thank you @FabienPapet for the PR.

**Comment by ThomasLandauer** [comment]
Is this fix really working?

My `Kernel::VERSION_ID` is 30306, and I still get the deprecation notice. It only disappears if I add this to my `services.yml`:
```yml
services:
    Cocur\Slugify\SlugifyInterface:
        alias: "cocur_slugify"
```

**Comment by florianeckerstorfer** [comment]
@ThomasLandauer Since I don't use Symfony right now, can anyone verify this?

**Comment by ThomasLandauer** [comment]
@FabienPapet you missed `Interface` ;-) I fixed it here https://github.com/cocur/slugify/pull/191/files

You need to clear your cache.

**Comment by FabienPapet** [comment]
Maybe it's worth to add both Interface and class FQN ? as this PR will add
Deprecation notices on people using just the classname

2017-10-13 15:01 GMT+02:00 Thomas Landauer <notifications@github.com>:

**Comment by ThomasLandauer** [comment]
You mean, if you inject it like this? `public function __construct(\Cocur\Slugify\Slugify $slugify)`

I wasn't aware that this would work. I suggested the other way here: https://github.com/cocur/slugify#symfony

@florianeckerstorfer What's the preferred way?

**Comment by florianeckerstorfer** [comment]
Sorry, I can't really say because I have no used this feature in Symfony (I'm no longer payed to write PHP code so this also will not change soon). I need your advice here?

Is it possible to add two aliases?

**Comment by FabienPapet** [comment]
Yes , this will work, this is what I did on a project. 
I forget to add doc about it when I submitted the PR,  fixed now
